name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - name: make directory build
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
